# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: aafcacf4-d862-483c-a5d9-5ea57118afc2;MulleObjC;no-all-load,no-bequeath,no-link,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjC no-header`
# Disable for this platform: `mulle-sourcetree mark MulleObjC no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleObjC no-cmake-sdk-<name>`
#
if( NOT MULLE_OBJC_HEADER)
   find_file( MULLE_OBJC_HEADER NAMES
      MulleObjC.h MulleObjC/MulleObjC.h
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
   )
   if( NOT MULLE_OBJC_HEADER AND NOT DEPENDENCY_IGNORE_SYSTEM_HEADERS)
      find_file( MULLE_OBJC_HEADER NAMES
         MulleObjC.h MulleObjC/MulleObjC.h
      )
   endif()
   message( STATUS "MULLE_OBJC_HEADER is ${MULLE_OBJC_HEADER}")

   #
   # Add MULLE_OBJC_HEADER to HEADER_ONLY_LIBRARIES list.
   # Disable with: `mulle-sourcetree mark MulleObjC no-cmake-add`
   #
   set( HEADER_ONLY_LIBRARIES
      ${MULLE_OBJC_HEADER}
      ${HEADER_ONLY_LIBRARIES}
   )
   if( MULLE_OBJC_HEADER)
      #
      # Inherit ObjC loader and link dependency info.
      # Disable with: `mulle-sourcetree mark MulleObjC no-cmake-inherit`
      #
      get_filename_component( _TMP_MULLE_OBJC_ROOT "${MULLE_OBJC_HEADER}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_NAME "${_TMP_MULLE_OBJC_ROOT}" NAME)
      get_filename_component( _TMP_MULLE_OBJC_ROOT "${_TMP_MULLE_OBJC_ROOT}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_ROOT "${_TMP_MULLE_OBJC_ROOT}" DIRECTORY)
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjC no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_NAME IN LISTS _TMP_MULLE_OBJC_NAME)
         set( _TMP_MULLE_OBJC_DIR "${_TMP_MULLE_OBJC_ROOT}/include/${_TMP_MULLE_OBJC_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_DIR}")
            # we only want top level INHERIT_OBJC_LOADERS, so disable them
            if( NOT NO_INHERIT_OBJC_LOADERS)
               set( NO_INHERIT_OBJC_LOADERS OFF)
            endif()
            list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
            set( NO_INHERIT_OBJC_LOADERS ON)
            #
            include( "${_TMP_MULLE_OBJC_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
            list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_DIR}")
            #
            unset( MULLE_OBJC_DEFINITIONS)
            include( "${_TMP_MULLE_OBJC_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE_OBJC_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_DIR} not found")
         endif()
      endforeach()
   else()
      # Disable with: `mulle-sourcetree mark MulleObjC no-require`
      message( SEND_ERROR "MULLE_OBJC_HEADER was not found in MulleObjC.h MulleObjC/MulleObjC.h")
   endif()
endif()
