# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: aafcacf4-d862-483c-a5d9-5ea57118afc2;MulleObjC;no-all-load,no-bequeath,no-link,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjC no-header`
# Disable for this platform: `mulle-sourcetree mark MulleObjC no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleObjC no-cmake-sdk-<name>`
#
if( NOT MULLE_OBJC_HEADER)
   find_file( MULLE_OBJC_HEADER NAMES MulleObjC.h MulleObjC/MulleObjC.h)
   message( STATUS "MULLE_OBJC_HEADER is ${MULLE_OBJC_HEADER}")

   #
   # Add MULLE_OBJC_HEADER to HEADER_ONLY_LIBRARIES list.
   # Disable with: `mulle-sourcetree mark MulleObjC no-cmake-add`
   #
   set( HEADER_ONLY_LIBRARIES
      ${MULLE_OBJC_HEADER}
      ${HEADER_ONLY_LIBRARIES}
   )
   if( MULLE_OBJC_HEADER)
      #
      # Inherit ObjC loader and link dependency info.
      # Disable with: `mulle-sourcetree mark MulleObjC no-cmake-inherit`
      #
      get_filename_component( _TMP_MULLE_OBJC_ROOT "${MULLE_OBJC_HEADER}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_NAME "${_TMP_MULLE_OBJC_ROOT}" NAME)
      get_filename_component( _TMP_MULLE_OBJC_ROOT "${_TMP_MULLE_OBJC_ROOT}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_ROOT "${_TMP_MULLE_OBJC_ROOT}" DIRECTORY)
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjC no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_NAME IN LISTS _TMP_MULLE_OBJC_NAME)
         set( _TMP_MULLE_OBJC_DIR "${_TMP_MULLE_OBJC_ROOT}/include/${_TMP_MULLE_OBJC_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_DIR}")
            # we only want top level INHERIT_OBJC_LOADERS, so disable them
            if( NOT NO_INHERIT_OBJC_LOADERS)
               set( NO_INHERIT_OBJC_LOADERS OFF)
            endif()
            list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
            set( NO_INHERIT_OBJC_LOADERS ON)
            #
            include( "${_TMP_MULLE_OBJC_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
            list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_DIR}")
            #
            unset( MULLE_OBJC_DEFINITIONS)
            include( "${_TMP_MULLE_OBJC_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE_OBJC_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_DIR} not found")
         endif()
      endforeach()
   else()
      # Disable with: `mulle-sourcetree mark MulleObjC no-require`
      message( FATAL_ERROR "MULLE_OBJC_HEADER was not found")
   endif()
endif()



#
# Generated from sourcetree: BEF48094-A626-4A85-9A13-49BF7BC0507D;MulleObjC muss no-bequeath sein, wegen dies und das;no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-cmake-sdk-<name>`
#
if( NOT MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY)
   find_library( MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY NAMES
      ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjC muss no-bequeath sein${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjC muss no-bequeath sein${CMAKE_STATIC_LIBRARY_SUFFIX}
      MulleObjC muss no-bequeath sein
      ${CMAKE_STATIC_LIBRARY_PREFIX} wegen dies und das${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX} wegen dies und das${CMAKE_STATIC_LIBRARY_SUFFIX}
       wegen dies und das
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
   )
   if( NOT MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
      find_library( MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjC muss no-bequeath sein${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjC muss no-bequeath sein${CMAKE_STATIC_LIBRARY_SUFFIX}
         MulleObjC muss no-bequeath sein
         ${CMAKE_STATIC_LIBRARY_PREFIX} wegen dies und das${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX} wegen dies und das${CMAKE_STATIC_LIBRARY_SUFFIX}
          wegen dies und das
      )
   endif()
   message( STATUS "MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY is ${MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY)
      #
      # Add MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-cmake-add`
      #
      list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY})
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_ROOT "${MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_ROOT "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_ROOT}" DIRECTORY)
      #
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_NAME "MulleObjC muss no-bequeath sein" " wegen dies und das")
         set( _TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_ROOT}/include/${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR}")
            #
            unset( MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DEFINITIONS)
            include( "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_NAME "MulleObjC muss no-bequeath sein" " wegen dies und das")
            set( _TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_FILE "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_ROOT}/include/${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_FILE}")
               list( APPEND INHERITED_OBJC_LOADERS ${_TMP_MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_FILE})
               break()
            endif()
         endforeach()
      endif()
   else()
      # Disable with: `mulle-sourcetree mark MulleObjC muss no-bequeath sein, wegen dies und das no-require-link`
      message( FATAL_ERROR "MULLE_OBJC_MUSS_NO_BEQUEATH_SEIN__WEGEN_DIES_UND_DAS_LIBRARY was not found")
   endif()
endif()


#
# Generated from sourcetree: 8c85d1ab-bece-4726-aa46-f9e9e4e7000a;mulle-atinit;no-cmake-searchpath,no-descend,no-dynamic-link,no-import,no-intermediate-link,no-public,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-atinit no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-atinit no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-atinit no-cmake-sdk-<name>`
#
if( NOT MULLE_ATINIT_LIBRARY)
   find_library( MULLE_ATINIT_LIBRARY NAMES
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_STATIC_LIBRARY_SUFFIX}
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
   )
   if( NOT MULLE_ATINIT_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
      find_library( MULLE_ATINIT_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_STATIC_LIBRARY_SUFFIX}
      )
   endif()
   message( STATUS "MULLE_ATINIT_LIBRARY is ${MULLE_ATINIT_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_ATINIT_LIBRARY)
      #
      # Add MULLE_ATINIT_LIBRARY to STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-add`
      #
      list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE_ATINIT_LIBRARY})
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_ATINIT_ROOT "${MULLE_ATINIT_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_ATINIT_ROOT "${_TMP_MULLE_ATINIT_ROOT}" DIRECTORY)
      #
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-dependency`
      #
      foreach( _TMP_MULLE_ATINIT_NAME "mulle-atinit")
         set( _TMP_MULLE_ATINIT_DIR "${_TMP_MULLE_ATINIT_ROOT}/include/${_TMP_MULLE_ATINIT_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE_ATINIT_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_ATINIT_DIR}")
            #
            include( "${_TMP_MULLE_ATINIT_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_ATINIT_DIR}")
            #
            unset( MULLE_ATINIT_DEFINITIONS)
            include( "${_TMP_MULLE_ATINIT_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE_ATINIT_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE_ATINIT_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_ATINIT_NAME "mulle-atinit")
            set( _TMP_MULLE_ATINIT_FILE "${_TMP_MULLE_ATINIT_ROOT}/include/${_TMP_MULLE_ATINIT_NAME}/MulleObjCLoader+${_TMP_MULLE_ATINIT_NAME}.h")
            if( EXISTS "${_TMP_MULLE_ATINIT_FILE}")
               list( APPEND INHERITED_OBJC_LOADERS ${_TMP_MULLE_ATINIT_FILE})
               break()
            endif()
         endforeach()
      endif()
   else()
      # Disable with: `mulle-sourcetree mark mulle-atinit no-require-link`
      message( FATAL_ERROR "MULLE_ATINIT_LIBRARY was not found")
   endif()
endif()


#
# Generated from sourcetree: c703e494-09ac-4a1f-bffc-bdb12a3af507;mulle-atexit;no-cmake-searchpath,no-descend,no-dynamic-link,no-import,no-intermediate-link,no-public,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-atexit no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-atexit no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-atexit no-cmake-sdk-<name>`
#
if( NOT MULLE_ATEXIT_LIBRARY)
   find_library( MULLE_ATEXIT_LIBRARY NAMES
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_STATIC_LIBRARY_SUFFIX}
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
   )
   if( NOT MULLE_ATEXIT_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
      find_library( MULLE_ATEXIT_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_STATIC_LIBRARY_SUFFIX}
      )
   endif()
   message( STATUS "MULLE_ATEXIT_LIBRARY is ${MULLE_ATEXIT_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_ATEXIT_LIBRARY)
      #
      # Add MULLE_ATEXIT_LIBRARY to STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-add`
      #
      list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE_ATEXIT_LIBRARY})
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_ATEXIT_ROOT "${MULLE_ATEXIT_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_ATEXIT_ROOT "${_TMP_MULLE_ATEXIT_ROOT}" DIRECTORY)
      #
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-dependency`
      #
      foreach( _TMP_MULLE_ATEXIT_NAME "mulle-atexit")
         set( _TMP_MULLE_ATEXIT_DIR "${_TMP_MULLE_ATEXIT_ROOT}/include/${_TMP_MULLE_ATEXIT_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE_ATEXIT_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_ATEXIT_DIR}")
            #
            include( "${_TMP_MULLE_ATEXIT_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_ATEXIT_DIR}")
            #
            unset( MULLE_ATEXIT_DEFINITIONS)
            include( "${_TMP_MULLE_ATEXIT_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE_ATEXIT_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE_ATEXIT_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_ATEXIT_NAME "mulle-atexit")
            set( _TMP_MULLE_ATEXIT_FILE "${_TMP_MULLE_ATEXIT_ROOT}/include/${_TMP_MULLE_ATEXIT_NAME}/MulleObjCLoader+${_TMP_MULLE_ATEXIT_NAME}.h")
            if( EXISTS "${_TMP_MULLE_ATEXIT_FILE}")
               list( APPEND INHERITED_OBJC_LOADERS ${_TMP_MULLE_ATEXIT_FILE})
               break()
            endif()
         endforeach()
      endif()
   else()
      # Disable with: `mulle-sourcetree mark mulle-atexit no-require-link`
      message( FATAL_ERROR "MULLE_ATEXIT_LIBRARY was not found")
   endif()
endif()
