# test runs on OS X, because llvm is not bottled
# in linuxbrew (at the moment 11/2016)
#
language: objective-c

before_install:
   - brew update
   - brew install mulle-kybernetik/software/mulle-build
   - brew install codeon-gmbh/software/mulle-clang

script:
   - mulle-build
   - mulle-test
