language: c

dist: xenial

before_install:
   - curl -sS https://www.codeon.de/dists/codeon-pub.asc | sudo apt-key add -
   - sudo echo "deb [arch=amd64] http://download.codeon.de `lsb_release -c -s` main" | sudo tee "/etc/apt/sources.list.d/codeon.de-main.list"  > /dev/null
   - curl -sS "https://www.mulle-kybernetik.com/dists/debian-admin-pub.asc" | sudo apt-key add -
   - echo "deb [arch=all] http://www.mulle-kybernetik.com `lsb_release -c -s` main" | sudo tee "/etc/apt/sources.list.d/mulle-kybernetik.com-main.list" > /dev/null
   - sudo apt-get update
   - sudo apt-get -y install mulle-clang cmake mulle-sde mulle-test

script:
   - mulle-sde craft
   - mulle-sde test
