# test runs on OS X, because llvm is not bottled
# in linuxbrew (at the moment 11/2016)
#
language: objective-c

before_install:
   - brew tap mulle-kybernetik/software
   - brew install mulle-build
   - brew tap codeon-gmbh/software
   - brew install mulle-clang

script:
   - mulle-build
   - mulle-test
