dist: trusty
sudo: required

script:
  - curl -L -O 'https://raw.githubusercontent.com/mulle-objc/mulle-objc-developer/release/install-ubuntu.sh'
  - chmod 755 install-ubuntu.sh
  - ./install-ubuntu.sh
  - ls
  - mulle-build -vv -V --bootstrap
  - mulle-test -vv -V
